Document: anwendung
Title: Debian anwendung Manual
Author: <insert document author here>
Abstract: This manual describes what anwendung is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/anwendung/anwendung.sgml.gz

Format: postscript
Files: /usr/share/doc/anwendung/anwendung.ps.gz

Format: text
Files: /usr/share/doc/anwendung/anwendung.text.gz

Format: HTML
Index: /usr/share/doc/anwendung/html/index.html
Files: /usr/share/doc/anwendung/html/*.html
